# Generated by Django 3.1.2 on 2021-06-02 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
