# Generated by Django 3.1.2 on 2021-06-03 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advertisements', '0003_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementsUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favorite', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='status',
            field=models.TextField(choices=[('OPEN', 'Открыто'), ('CLOSED', 'Закрыто'), ('DRAFT', 'Черновик')], default='OPEN'),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_advertisement', models.ManyToManyField(related_name='favorite_advertisements', through='advertisements.AdvertisementsUsers', to='advertisements.Advertisement')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='advertisementsusers',
            name='advertisement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_favorite', to='advertisements.advertisement'),
        ),
        migrations.AddField(
            model_name='advertisementsusers',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_favorite', to='advertisements.person'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='persons_in_favorites',
            field=models.ManyToManyField(related_name='persons_in_favorites', through='advertisements.AdvertisementsUsers', to='advertisements.Person'),
        ),
    ]
